### ISSUE TITLE
Pixel mapping issues?

### ISSUE THREAD

**Issue by asolochek** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#16]
I'm not sure if this is a problem with the wrapper, or a problem in the ESPHome display component, but I thought I'd start here and work my way down.

I have the adafruit Matrix Portal S3 connected to this 64x32 display: https://www.adafruit.com/product/5036

I noticed the font rendering was crap, and to try to narrow down the problem I wrote some yaml to display a couple of vertical lines:

```
display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    R1_pin: 42
    G1_pin: 41
    B1_pin: 40
    R2_pin: 38
    G2_pin: 39
    B2_pin: 37
    A_pin: 45
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2
    brightness: 100
    update_interval: 8ms
    i2sspeed: HZ_20M
    rotation: 0
    lambda: |-
      it.line(1,1,1,30);
      it.line(11,1,11,30);
      it.line(21,1,21,30);
      it.line(31,1,31,30);
      it.line(41,1,41,30);
      it.line(51,1,51,30);
      it.line(61,1,61,30);
```
As you can see in the attached video, the lines are not evenly spaced as expected, and there are various adjacent pixels flickering on, and the lines themselves are not all solid. It looks like perhaps somewhere internally the size of the display is different so we're getting weird aliasing. Is this something that might be happening in this wrapper, or is this a problem with the display component? When I set the rotation to 180, the artifacts remain on the same physical side of the screen, so the issue would seem to be someplace between where that rotation is applied and the hardware.

Note that I did test some demos using circuitpython to verify the issue isn't the display.

Any help in tracking this issue down would be appreciated.

https://github.com/TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper/assets/1464528/9de611e5-8b8a-4df1-9770-7c96e58db42b

**Comment by TillFleisch** [comment]
This is probably neither an issue with this wrapper nor with ESPHome's display component.
To me, this looks like a wiring or power issue. I would recommend checking the following things:
 - make sure everything is properly grounded
 - make sure the power supply is noise-free and sufficient for the job
 - make sure you are using short wires and all that all connections are solid
 - play around with the `latch_blanking` value

I would strongly advise you to look for similar issues within the [library repository which this wrapper wraps around](https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#master) and read up on documentation there. The issues 134 and 145 may be a good place to start.

**Comment by asolochek** [comment]
That pointer led me to trying some test code using that library directly and I discovered the issue was the clock phase. After adding argument it works perfectly in esphome. Thank you!
