### ISSUE TITLE
P10 outdoor display

### ISSUE THREAD

**Issue by tiimsvk** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#17]
Is compatible display whit this custom component?
https://www.aliexpress.com/item/1005004049924779.html
Thanks

**Comment by TillFleisch** [comment]
Sorry for the late reply, the notification mail went unnoticed.

You can use any display that is compatible with the [ESP32-HUB75-MatrixPanel-DMA](https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA#master) project.
Please look up the restriction, which apply in the linked repository (in particular [this section](https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA?tab=readme-ov-file#supported-panel-can-types)) and determine the chipset which is used by the linked panel.
