### ISSUE TITLE
Unable to compile with  example code with Esphome

### ISSUE THREAD

**Issue by nbjm** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#7]
I get his error whenever I try to write some code for a hub75 display connected to a esp32trinity

  _**_File "/config/esphome/.esphome/external_components/82436398/components/matrix_display/display.py", line 150, in to_code
    config[CONF_LAMBDA], [(display.DisplayRef, "it")], return_type=cg.void
AttributeError: module 'esphome.components.display' has no attribute 'DisplayRef'_**_

I have tried the test example code, and any time a display component is used it fails to compile.
     **_it.line(0, 0, 50, 50);_**
or 
      **_it.print(0, 0, id(roboto), "Hello World!");_**

Please advise as I am not sure how to fix this?

**Comment by TillFleisch** [comment]
Please make sure you are using ESPHome 2023.7.0 or higher.

**Comment by nbjm** [comment]
Thank you that was the issue.

**Comment by nbjm** [comment]
Thank you that was it.
